### ISSUE TITLE
 Installing Cypress 

### ISSUE THREAD

**Issue by sholtomaud** [mikeal/webtorrent-component#5]
Why does webtorrent-element install cypress from ```npm i webtorrent-element```?

**Comment by mikeal** [comment]
I think it's a sub-dependency of the testing tools. It won't show up in the bundle though, it's just there for tests.

**Comment by sholtomaud** [comment]
Yeah-nah, whenever I use npm to install the webtorrent-element it pulls down cypress. But it shouldn't should it?

**Comment by mikeal** [comment]
yes,`npm install` sets up the module for development and will install devDependencies. if you don't want the dev deps you need to use --production.

**Comment by sholtomaud** [comment]
ahhhhhhhhhh! right okay. Cheers :)
